In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
 """    Yes, there will be a difference in the data type of the elements present in both the list_ and array_list
     variables after you create array_list with dtype=int.
     The elements in the array_list will be converted to integers,
     while the elements in the list_ variable will remain strings."""


import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

shape = num_array.shape

size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
import numpy as np

zero_matrix = np.zeros((3, 3))

print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
    [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]